# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x0brpc_package\"0\n\x0bRecoRequest\x12!\n\x05video\x18\x01 \x03(\x0b\x32\x12.rpc_package.Video\"\"\n\x05Video\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"0\n\tRecoReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nscore_list\x18\x02 \x03(\x01\x32L\n\x0bRecoService\x12=\n\x07SayReco\x12\x18.rpc_package.RecoRequest\x1a\x16.rpc_package.RecoReply\"\x00\x62\x06proto3')



_RECOREQUEST = DESCRIPTOR.message_types_by_name['RecoRequest']
_VIDEO = DESCRIPTOR.message_types_by_name['Video']
_RECOREPLY = DESCRIPTOR.message_types_by_name['RecoReply']
RecoRequest = _reflection.GeneratedProtocolMessageType('RecoRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOREQUEST,
  '__module__' : 'video_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.RecoRequest)
  })
_sym_db.RegisterMessage(RecoRequest)

Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), {
  'DESCRIPTOR' : _VIDEO,
  '__module__' : 'video_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.Video)
  })
_sym_db.RegisterMessage(Video)

RecoReply = _reflection.GeneratedProtocolMessageType('RecoReply', (_message.Message,), {
  'DESCRIPTOR' : _RECOREPLY,
  '__module__' : 'video_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.RecoReply)
  })
_sym_db.RegisterMessage(RecoReply)

_RECOSERVICE = DESCRIPTOR.services_by_name['RecoService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECOREQUEST._serialized_start=28
  _RECOREQUEST._serialized_end=76
  _VIDEO._serialized_start=78
  _VIDEO._serialized_end=112
  _RECOREPLY._serialized_start=114
  _RECOREPLY._serialized_end=162
  _RECOSERVICE._serialized_start=164
  _RECOSERVICE._serialized_end=240
# @@protoc_insertion_point(module_scope)
