# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import video_pb2 as video__pb2


class RecoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayReco = channel.unary_unary(
                '/rpc_package.RecoService/SayReco',
                request_serializer=video__pb2.RecoRequest.SerializeToString,
                response_deserializer=video__pb2.RecoReply.FromString,
                )


class RecoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayReco(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayReco': grpc.unary_unary_rpc_method_handler(
                    servicer.SayReco,
                    request_deserializer=video__pb2.RecoRequest.FromString,
                    response_serializer=video__pb2.RecoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_package.RecoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayReco(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc_package.RecoService/SayReco',
            video__pb2.RecoRequest.SerializeToString,
            video__pb2.RecoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
