# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='content.proto',
  package='content_grpc_package',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcontent.proto\x12\x14\x63ontent_grpc_package\"K\n\x0bRecoRequest\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\x05\x12\x12\n\nchannel_id\x18\x02 \x01(\t\x12\x13\n\x0brequest_num\x18\x03 \x01(\x05\"W\n\x0cRecoResponse\x12.\n\x07\x63ontent\x18\x01 \x03(\x0b\x32\x1d.content_grpc_package.Content\x12\x17\n\x0f\x63ontent_id_list\x18\x02 \x03(\x05\"3\n\x07\x43ontent\x12\x12\n\ncontent_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\x05\x32\x61\n\x0bRecoService\x12R\n\x07RecoSys\x12!.content_grpc_package.RecoRequest\x1a\".content_grpc_package.RecoResponse\"\x00\x62\x06proto3'
)




_RECOREQUEST = _descriptor.Descriptor(
  name='RecoRequest',
  full_name='content_grpc_package.RecoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_uuid', full_name='content_grpc_package.RecoRequest.device_uuid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='content_grpc_package.RecoRequest.channel_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_num', full_name='content_grpc_package.RecoRequest.request_num', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=114,
)


_RECORESPONSE = _descriptor.Descriptor(
  name='RecoResponse',
  full_name='content_grpc_package.RecoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='content_grpc_package.RecoResponse.content', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_id_list', full_name='content_grpc_package.RecoResponse.content_id_list', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=203,
)


_CONTENT = _descriptor.Descriptor(
  name='Content',
  full_name='content_grpc_package.Content',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_id', full_name='content_grpc_package.Content.content_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_type', full_name='content_grpc_package.Content.content_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=256,
)

_RECORESPONSE.fields_by_name['content'].message_type = _CONTENT
DESCRIPTOR.message_types_by_name['RecoRequest'] = _RECOREQUEST
DESCRIPTOR.message_types_by_name['RecoResponse'] = _RECORESPONSE
DESCRIPTOR.message_types_by_name['Content'] = _CONTENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecoRequest = _reflection.GeneratedProtocolMessageType('RecoRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOREQUEST,
  '__module__' : 'content_pb2'
  # @@protoc_insertion_point(class_scope:content_grpc_package.RecoRequest)
  })
_sym_db.RegisterMessage(RecoRequest)

RecoResponse = _reflection.GeneratedProtocolMessageType('RecoResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECORESPONSE,
  '__module__' : 'content_pb2'
  # @@protoc_insertion_point(class_scope:content_grpc_package.RecoResponse)
  })
_sym_db.RegisterMessage(RecoResponse)

Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), {
  'DESCRIPTOR' : _CONTENT,
  '__module__' : 'content_pb2'
  # @@protoc_insertion_point(class_scope:content_grpc_package.Content)
  })
_sym_db.RegisterMessage(Content)



_RECOSERVICE = _descriptor.ServiceDescriptor(
  name='RecoService',
  full_name='content_grpc_package.RecoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=258,
  serialized_end=355,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecoSys',
    full_name='content_grpc_package.RecoService.RecoSys',
    index=0,
    containing_service=None,
    input_type=_RECOREQUEST,
    output_type=_RECORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOSERVICE)

DESCRIPTOR.services_by_name['RecoService'] = _RECOSERVICE

# @@protoc_insertion_point(module_scope)
