# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='video.proto',
  package='video_grpc_package',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bvideo.proto\x12\x12video_grpc_package\"X\n\x0bRecoRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nchannel_id\x18\x02 \x01(\t\x12\x0f\n\x07network\x18\x03 \x01(\t\x12\x13\n\x0brequest_num\x18\x04 \x01(\x05\"O\n\x0cRecoResponse\x12(\n\x05video\x18\x01 \x03(\x0b\x32\x19.video_grpc_package.Video\x12\x15\n\rvideo_id_list\x18\x02 \x03(\x05\"7\n\x05Video\x12\x10\n\x08video_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\x32]\n\x0bRecoService\x12N\n\x07RecoSys\x12\x1f.video_grpc_package.RecoRequest\x1a .video_grpc_package.RecoResponse\"\x00\x62\x06proto3')
)




_RECOREQUEST = _descriptor.Descriptor(
  name='RecoRequest',
  full_name='video_grpc_package.RecoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='video_grpc_package.RecoRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='video_grpc_package.RecoRequest.channel_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network', full_name='video_grpc_package.RecoRequest.network', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_num', full_name='video_grpc_package.RecoRequest.request_num', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=123,
)


_RECORESPONSE = _descriptor.Descriptor(
  name='RecoResponse',
  full_name='video_grpc_package.RecoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video', full_name='video_grpc_package.RecoResponse.video', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_id_list', full_name='video_grpc_package.RecoResponse.video_id_list', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=204,
)


_VIDEO = _descriptor.Descriptor(
  name='Video',
  full_name='video_grpc_package.Video',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='video_grpc_package.Video.video_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='video_grpc_package.Video.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='video_grpc_package.Video.score', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=261,
)

_RECORESPONSE.fields_by_name['video'].message_type = _VIDEO
DESCRIPTOR.message_types_by_name['RecoRequest'] = _RECOREQUEST
DESCRIPTOR.message_types_by_name['RecoResponse'] = _RECORESPONSE
DESCRIPTOR.message_types_by_name['Video'] = _VIDEO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecoRequest = _reflection.GeneratedProtocolMessageType('RecoRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOREQUEST,
  '__module__' : 'video_pb2'
  # @@protoc_insertion_point(class_scope:video_grpc_package.RecoRequest)
  })
_sym_db.RegisterMessage(RecoRequest)

RecoResponse = _reflection.GeneratedProtocolMessageType('RecoResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECORESPONSE,
  '__module__' : 'video_pb2'
  # @@protoc_insertion_point(class_scope:video_grpc_package.RecoResponse)
  })
_sym_db.RegisterMessage(RecoResponse)

Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), {
  'DESCRIPTOR' : _VIDEO,
  '__module__' : 'video_pb2'
  # @@protoc_insertion_point(class_scope:video_grpc_package.Video)
  })
_sym_db.RegisterMessage(Video)



_RECOSERVICE = _descriptor.ServiceDescriptor(
  name='RecoService',
  full_name='video_grpc_package.RecoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=263,
  serialized_end=356,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecoSys',
    full_name='video_grpc_package.RecoService.RecoSys',
    index=0,
    containing_service=None,
    input_type=_RECOREQUEST,
    output_type=_RECORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOSERVICE)

DESCRIPTOR.services_by_name['RecoService'] = _RECOSERVICE

# @@protoc_insertion_point(module_scope)
